<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>netstandard2.0;net8.0;net461;net452</TargetFrameworks>
		<LangVersion>latest</LangVersion>

		<Company>ApeFree</Company>
		<Authors>Guijie Lee</Authors>
		<Copyright>Copyright © 2022-2026 ApeFree, All Rights Reserved.</Copyright>
		<GeneratePackageOnBuild Condition="'$(Configuration)' == 'Release'">true</GeneratePackageOnBuild>
		<Title>ApeFree.Cake2D</Title>
		<Product>ApeFree.Cake2D</Product>
		<Description>轻量级、图层化、面向对象抽象的 2D 平面绘图与交互框架。</Description>
		<Version>0.1.0-beta</Version>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<PackageIcon>ApeFree_64px.png</PackageIcon>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
		<PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
	</PropertyGroup>

	<ItemGroup>
		<None Include="README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="..\ApeFree_64px.png">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

</Project>