<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0-windows;net6.0-windows;net462</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <UseWindowsForms>true</UseWindowsForms>
    <Company>ApeFree</Company>
    <Authors>Guijie Lee</Authors>
    <Copyright>Copyright © 2022-2026 ApeFree, All Rights Reserved.</Copyright>
    <GeneratePackageOnBuild Condition="'$(Configuration)' == 'Release'">true</GeneratePackageOnBuild>
    <Title>Cake2D.Skia</Title>
    <Product>ApeFree.Cake2D.Skia</Product>
    <Description>基于 SkiaSharp 的 Cake2D 渲染接口与控件库</Description>
    <Version>1.0.2.1-alpha260907</Version>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <PackageIcon>ApeFree_64px.png</PackageIcon>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SkiaSharp" Version="2.88.9" />
    <PackageReference Include="SkiaSharp.Views.WindowsForms" Version="2.88.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ApeFree.Cake2D\ApeFree.Cake2D.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\ApeFree_64px.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>